name: Build Plugin

on: workflow_dispatch

jobs:
  build:
    timeout-minutes: 8
    runs-on: ubuntu-20.04
    steps:
      - name: Initial Checks
        run: |
          if [ "${{ github.event.event_type }}" != "plugin_build" ]; then
            echo "No client payload data detected! This workflow can only be run with an HTTP request or using the backend.";
            exit 1;
          fi

      - name: Checkout Target Plugin Repo
        uses: actions/checkout@v2
        with:
          ref: "${{ github.event.client_payload.targetCommit }}"
          repository: "${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }}"
          path: "plugin"

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Plugin
        run: |
          cd $GITHUB_WORKSPACE/plugin
          chmod +x gradlew
          CI=true ./gradlew :${{ github.event.client_payload.plugin }}:make

      - name: Checkout Plugins Store
        uses: actions/checkout@v2
        with:
          path: "plugins-store"

      - name: Push builds
        run: |
          cp $GITHUB_WORKSPACE/plugin/**/${{ github.event.client_payload.plugin }}/build/${{ github.event.client_payload.plugin }}.zip
          cd $GITHUB_WORKSPACE/plugins-store
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *
          git commit -m "Build ${{ github.event.client_payload.plugin }}" || exit 0
          git push
