name: Build Plugin

on:
  workflow_dispatch:
    inputs:
      owner:
        type: string
        description: The owner of the plugin's repository.
        required: true
      repository:
        type: string
        description: The repository name.
        required: true
        default: redditvanced-plugins
      plugin:
        type: string
        description: The plugin to build.
        required: true
      ref:
        type: string
        description: The target commit hash of the repo to clone or branch name.
        required: true

jobs:
  build:
    timeout-minutes: 8
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Target Plugin Repo
        uses: actions/checkout@v2
        with:
          ref: "${{ github.event.inputs.ref }}"
          repository: "${{ github.event.inputs.owner }}/${{ github.event.inputs.repository }}"
          path: "plugin"

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu

      - name: Setup Android SDK
        uses: android-actions/setup-android@1685c3d8669829f192d94fcad89eba25ce558bb2

      - name: Build Plugin
        run: |
          cd $GITHUB_WORKSPACE/plugin
          chmod +x gradlew
          CI=true ./gradlew :${{ github.event.inputs.plugin }}:make

      - name: Checkout Plugins Store
        uses: actions/checkout@v2
        with:
          path: "plugins-store"

      - name: Push builds
        run: |
          cp $GITHUB_WORKSPACE/plugin/**/build/*.zip
          cd $GITHUB_WORKSPACE/plugins-store
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ${{ github.event.inputs.plugin }}.zip
          git commit -m "${{ github.event.inputs.plugin }} ${{ github.event.inputs.owner }}/${{ github.event.inputs.repository }}@${{ github.event.inputs.ref }}" || exit 0
          git push
